// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDhtaxuqXT633xkYqbR-x1xvThL9maI0bs',
    appId: '1:57833784009:web:20e0e01d1f8b5e6d914318',
    messagingSenderId: '57833784009',
    projectId: 'resee-app',
    authDomain: 'resee-app.firebaseapp.com',
    storageBucket: 'resee-app.firebasestorage.app',
    measurementId: 'G-TZGVJ22R7J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBci65bMJopNnideOsXGSeVEDf467-DTtg',
    appId: '1:57833784009:android:7f203adb17bf22f9914318',
    messagingSenderId: '57833784009',
    projectId: 'resee-app',
    storageBucket: 'resee-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDy9P2MYqYJaWHqxlwKFY7bgn2n1oNhh1w',
    appId: '1:57833784009:ios:e96c31516145ca59914318',
    messagingSenderId: '57833784009',
    projectId: 'resee-app',
    storageBucket: 'resee-app.firebasestorage.app',
    iosClientId: '57833784009-r2s57m6bctfbj1gnoqrpiu123d2sd8dn.apps.googleusercontent.com',
    iosBundleId: 'com.example.resee',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDy9P2MYqYJaWHqxlwKFY7bgn2n1oNhh1w',
    appId: '1:57833784009:ios:e96c31516145ca59914318',
    messagingSenderId: '57833784009',
    projectId: 'resee-app',
    storageBucket: 'resee-app.firebasestorage.app',
    iosClientId: '57833784009-r2s57m6bctfbj1gnoqrpiu123d2sd8dn.apps.googleusercontent.com',
    iosBundleId: 'com.example.resee',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDhtaxuqXT633xkYqbR-x1xvThL9maI0bs',
    appId: '1:57833784009:web:b5140df5adc1b94f914318',
    messagingSenderId: '57833784009',
    projectId: 'resee-app',
    authDomain: 'resee-app.firebaseapp.com',
    storageBucket: 'resee-app.firebasestorage.app',
    measurementId: 'G-E602DLZFV9',
  );
}
